### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by gBarlach** [rimi-itk/ding_pretix#5]
**Describe the bug**
Når jeg opretter et nyt arrangement på https://dpl-cms.srvitkhulk.itkdev.dk/ og gemmer, får jeg flg. fejl:

Successfully saved the Syv sprælske sværdfisk event series
Status message icon
A total of 1 event instances were created as part of this event series.
Error message
Error warning icon
Warning: Undefined array key 0 in Drupal\dpl_pretix\EntityHelper->createEventInstance() (line 401 of sites/default/files/modules_local/dpl_pretix/src/EntityHelper.php).
Error warning icon
Warning: Trying to access array offset on value of type null in Drupal\dpl_pretix\EntityHelper->createEventInstance() (line 401 of sites/default/files/modules_local/dpl_pretix/src/EntityHelper.php).
Error warning icon
Error synchronizing eventseries:16: Cannot create quota for sub-event 16 on event test-16
Error warning icon
Error synchronizing eventseries:16: Client error: `POST https://pretix.dpl-cms.srvitkhulk.itkdev.dk/api/v1/organizers/dpl-cms/events/betal/clone/` resulted in a `400 Bad Request` response: {"slug":["This slug has already been used for a different event."]}

Arrangementet har ikke tidligere været oprettet, hverken i https://dpl-cms.srvitkhulk.itkdev.dk/ eller i https://pretix.dpl-cms.srvitkhulk.itkdev.dk/

Trods fejlmeddelelsen i dpl-cms **bliver arrangementet faktisk oprettet** ovre i https://pretix.dpl-cms.srvitkhulk.itkdev.dk/ **- se [vedlagte skærmdump](https://pretix.dpl-cms.srvitkhulk.itkdev.dk/control/event/dpl-cms/test-16/)

**To Reproduce**

login i https://dpl-cms.srvitkhulk.itkdev.dk/ som admin
Klik på content - add content 
Klik på event series
Udfyld skabelonen og klik på save

**Expected behavior**
Jeg forventer at systemet bekræfter at arrangementet er gemt med succes i dpl-com uden fejlmedd. af nogen art. Og jeg ville egentlig også gerne have bekræftelse på, at det var gemt i Pretix med success. 

**Additional context**
[Sværdfisk aaa - DPL CMS - Logged in - dpl-cms.srvitkhulk.itkdev.dk.pdf](https://github.com/user-attachments/files/16715869/Svaerdfisk.aaa.-.DPL.CMS.-.Logged.in.-.dpl-cms.srvitkhulk.itkdev.dk.pdf)
![Skærmbillede 2024-08-22 kl  20 01 25](https://github.com/user-attachments/assets/e3b44400-531b-42f6-89b2-26a558a8c8e1)

**Comment by rimi-itk** [comment]
Tak for den grundige fejlrapport, @gBarlach. Fejlen var nem at reproducere, men bøvlet at finde (det var noget med håndtering af produktvarianter i pretix). Fejlen er rettet i https://www.drupal.org/project/dpl_pretix/releases/10.0.0-alpha6.
