### ISSUE TITLE
Fejl ved oprettelse af nyt arrangement: 400 Bad Request` response: {"slug":["This slug has already been used for a different event."]}

### ISSUE THREAD

**Issue by gBarlach** [rimi-itk/ding_pretix#6]
**Describe the bug**
Test af Release10.0.0-alpha6 på https://dpl-cms.srvitkhulk.itkdev.dk/

Når jeg opretter et helt nyt arrangement på https://dpl-cms.srvitkhulk.itkdev.dk/ og klikker save, får jeg flg. fejl:

Successfully saved the Gitte - tester. Vilde problemer event series
Status message icon
A total of 1 event instances were created as part of this event series.
Error message
Error warning icon
Error synchronizing eventseries:22: Cannot create sub-event for event test-22
Error warning icon
Error synchronizing eventseries:22: Client error: `POST https://pretix.dpl-cms.srvitkhulk.itkdev.dk/api/v1/organizers/dpl-cms/events/betal/clone/` resulted in a `400 Bad Request` response: {"slug":["This slug has already been used for a different event."]}

Arrangementet bliver dog oprettet ovre i https://pretix.dpl-cms.srvitkhulk.itkdev.dk

**To Reproduce**
Jeg følger instruktionerne og opgraderer https://dpl-cms.srvitkhulk.itkdev.dk/ til [10.0.0-alpha6](https://www.drupal.org/project/dpl_pretix/releases/10.0.0-alpha6) - 23 August 2024
Jeg går derefter til content - add content - event series
Jeg udfylder skabelonen, herunder vælger jeg 'template event - betal'
Jeg klikker på 'save'
Herefter kommer https://dpl-cms.srvitkhulk.itkdev.dk/ med de meddelelser, der fremgår af bugbeskrivelsen ovenfor.

[
![Skærmbillede 2024-08-26 kl  10 00 03](https://github.com/user-attachments/assets/0c7bf60f-ba69-4e64-b2d8-68a77cbc2b53)
![Skærmbillede 2024-08-26 kl  09 54 26](https://github.com/user-attachments/assets/67c3be49-7d68-466e-bce0-33cefb68c0d2)
[Create Default Event - DPL CMS - Logged in - dpl-cms.srvitkhulk.itkdev.dk.pdf](https://github.com/user-attachments/files/16746027/Create.Default.Event.-.DPL.CMS.-.Logged.in.-.dpl-cms.srvitkhulk.itkdev.dk.pdf)
](url)
![Skærmbillede 2024-08-23 kl  15 30 06](https://github.com/user-attachments/assets/85967f37-6ff8-446d-b38f-3ecc82ef5c08)
![Skærmbillede 2024-08-23 kl  15 29 38](https://github.com/user-attachments/assets/c0862e1c-0157-4382-a3c1-f9174c775c22)
![Skærmbillede 2024-08-23 kl  15 29 20](https://github.com/user-attachments/assets/5380b505-d269-488d-90b1-d595e349b79d)
![Skærmbillede 2024-08-23 kl  15 29 00](https://github.com/user-attachments/assets/d11e4419-ba41-4b99-b8d2-21e14773d1ee)

Link til det nyoprettede arrangement i dpl-cms: 
https://dpl-cms.srvitkhulk.itkdev.dk/hovedbiblioteket/events/gitte-tester-vilde-problemer
Link til det nyoprettede arrangement  i pretix: https://pretix.dpl-cms.srvitkhulk.itkdev.dk/control/event/dpl-cms/test-20/

**Expected behavior**
Jeg forventer at arrangementet bliver oprettet, gemt og skubbet over i pretix og at jeg får en bekræftelse på dette, uden der kommer fejlmeddelelser.

**Additional context**

**Comment by rimi-itk** [comment]
Fixed in https://www.drupal.org/project/dpl_pretix/releases/10.0.0-alpha7.
